### PR TITLE
Added docker support

### PR DESCRIPTION
**Pull request by dalareo**

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey,
thanks @dalareo ! 

However, also notice that someone recently started maintaining a docker version -
[ linked to from our Wiki](https://hub.docker.com/r/moritzf/fiduswriter/). I don't really know much about docker, but probably a good idea if you guys could coordinate? @moritzfl

If you two could decide what the best way forward is for docker, then I can merge what you come up with if you also click through the CLA (see CLAhub notice above).

**Comment by moritzfl** [comment]
Hi,
I looked at the PR - I am just guessing here but to me it seems like @dalareo looked at my version of the Dockerfile (looks kind of similar) and integrated the configuration through docker-variables instead of the configuration.py that I just reused from the fiduswriter-project.
Those adjustments should mean a relatively low effort in terms of maintenance as @dalareo  found a simple way to implement them but still introduce a layer on top of what my build currently does. Otherwise both builds technically fulfill the same task equally well. Both builds are not terribly different but then different enough to require a couple of decisions :-P

Some decisions that should be made by the core fiduswriter team in this regard:
- official integration into main project vs separate project
- if the docker build is integrated into your project: Who maintains the build if the core team does not have docker as a priority and can someone take over if @dalareo  drops out? In every case I would open an official fiduswriter account on docker hub to run automated builds if it is a direct part of the fiduswriter-project. If the answer to this question is unclear you risk problems in the project due to docker. Once you officially integrate docker support in your project moving back will upset users.  This is kind of linked to the next point as my build had the aim to keep complexity from the docker side (coding wise) as low as possible so that anyone could take over with very little information. @dalareo s build is simple enough right now but docker builds tend to get more complex as the project progresses.
- Are environment variables with *a bit* more complexity and maintenance wanted or is the configuration-file  fine?
- consider changes to the default configuration in @dalareo s docker build (deviations from fiduswriters default configuration)

**Comment by johanneswilm** [comment]
@moritzfl Thanks for this summary. We will discuss these points and come back with an answer. Just to be clear, were are not against Docker in any way. It's just that maintaining just one install procedure requires a substantiual amount of time. Other users have previously asked us for extra install instructions/adjustments for Debian or Windows, and we would just like not to overstretch otuselves and actually get to improve the product and not just spend time trying to get the install to work on different platforms.

**Comment by dalareo** [comment]
Having a separate repo for docker-compatible version is a good idea if there is no "official support", I agree @moritzfl.

I am still trying to setup the app properly. Allowed hosts configuration is harder than it seemd first with os environment variables. Any help, @moritzfl ?

**Comment by johanneswilm** [comment]
Ok, it sounds like you two agree then. For now I would indeed prefer external support as logn as @moritzfl offers it. Maybe he can make use of some of the advances @dalareo provided?

I have followed your commits related to the allowed hosts. Given that this is something required by Django, I assume that there is some general Django solution to this problem, wouldn't there be?

**Pull request closed without merging**
