### PR TITLE
Collapsible comments

### PR DESCRIPTION
**Pull request by ArupPatel**
### PR for making the comments collapsible for saving space and uncrowded view:

- Comments are made collapsible: if the comments have some answer/replies, it will be hidden in the inactive state, and in the active state all the answers/replies will be shown to the user
- If the number of replies/answers in the comments is >4, the comment container will be made scrollable. When the comment container is made scrollable, on adding the new answer/replies the scrollbar move to the latest comment.
- If the comment is a long one(>68 characters), only the first 68 characters are shown, and the rest hidden with a show-more button. The show more button will open up the full comment.
- The answer-editor for comment is now fixed to the bottom of the margin-box, so comments will be scrollable but not the answer editor.
- The marginbox options menu for comment and answer also have been changed. A template has been created for it, so now when someone clicks on the show-margin box options a new div is added to the body with the options(edit, assigned, etc), and once the action is selected the div is removed from the body. These changes are made because the menu was coming under the scroll view of the comment.

collapsed view:
image

uncollapsed view:
image
image

long comments views:
image
image
image

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @ArupPatel ,
this looks good! A few minor issues:

* Switch to hamburger menu from kebab menu: My understanding is that kebab menu is used for options and hamburger menu for navigation. Given that the menu contains options, I think it should be the kebab menu icon. Or am I missing something?

* Comment hamburger menu opening - It now opens to the right (before it opened to the left), going out into the margin of the screen. On smaller screens the menu is cut off in the middle. Ideally, it should use ContentMenu, which should ensure that it will always stay on the screen.

* Scrolling when writing a long comment. This is nice - when you write a very long comment, eventually the text box doesn't grow any further and instead scroll bars are added. Unfortunately the same doesn't happen with comment answers. It would be good to get the same functionality for comment answers.

**Comment by johanneswilm** [comment]
I get some JS errors:

"Got error: 
	context: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
	details: http://localhost:8000/document/13/: 0: ResizeObserver loop limit exceeded
	user: johannes

"
ERROR Got error: 
	context: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
	details: http://localhost:8000/static/js/21-1608298138.js: 12: Uncaught TypeError: Cannot set property 'innerText' of null, 47426, TypeError: Cannot set property 'innerText' of null
    at http://localhost:8000/static/js/21-1608298138.js:12:47426
    at NodeList.forEach (<anonymous>)
    at ze.closeAllLongComments (http://localhost:8000/static/js/21-1608298138.js:12:47310)
    at HTMLBodyElement.<anonymous> (http://localhost:8000/static/js/21-1608298138.js:12:34532)
	user: johannes
ERROR:javascript_error:Got error: 
	context: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
	details: http://localhost:8000/static/js/21-1608298138.js: 12: Uncaught TypeError: Cannot set property 'innerText' of null, 47426, TypeError: Cannot set property 'innerText' of null
    at http://localhost:8000/static/js/21-1608298138.js:12:47426
    at NodeList.forEach (<anonymous>)
    at ze.closeAllLongComments (http://localhost:8000/static/js/21-1608298138.js:12:47310)
    at HTMLBodyElement.<anonymous> (http://localhost:8000/static/js/21-1608298138.js:12:34532)
	user: johannes

""

**Comment by ArupPatel** [comment]
Hi @johanneswilm, 
Thanks for the review and suggestion. I will work on the fixes.
Regarding switching to the hamburger style menu, it is only for the first comment because it has options to delete and resolve the whole comment-answers chain, so wanted it to be a little more distinguishable/different from others.

**Comment by johanneswilm** [comment]
Ok, I understand about wanting to distinguish, but the hamburger menu ickn
has a specific meaning that we are not using here, so I think we need to go
back to the three dots. Maybe we can make the ones for answers slightly
smaller or distinguish them in some other way?

**Comment by johanneswilm** [comment]
@ArupPatel Looks nice. Could you also make sure the strings "show more" and "show less" are inside of gettext()? Like this: `gettext("show more")`. Else the translation system doesn't pick those strings up.

**Comment by ArupPatel** [comment]
### Changelog:

- Switched menu style from hamburger to kebab.
- The comment menu now opening to the left. It is now completely visible for smaller screens.
- Made prosemirror wrapper for comment and answer editor as scrollable.
- fix for Error: "cannot set property 'innerText' of null" in closeAllLongComments function
- Added gettext() for collapsible buttons
image

**Comment by ArupPatel** [comment]
> @ArupPatel Looks nice. Could you also make sure the strings "show more" and "show less" are inside of gettext()? Like this: `gettext("show more")`. Else the translation system doesn't pick those strings up.

Hey @johanneswilm,
I have added the gettext() for show-more/less and replies as per your suggestion, but they are not being translated for some reason and I also noticed something weird. When I put  "Assign" word in gettext() it is not being translated to other languages but if I put "Assigned to" it is getting translated. Do you have any idea regarding this?

**Comment by johanneswilm** [comment]
@ArupPatel Yes, that is because someone needs to write the translation first. The term "Assigned to" is already in the translation database, so that's why it can translate that already. After I have merged your code, I will then update translations for the languages we are supporting through POedit. German, Spanish and Portuguese are currently checked by people who know those languages. French, Italian and Bulgarian translations were contributed some years ago by native speaker, but currently all updates are just automatic Google Translate translations as there have been no further contributions for a while now.

Is this ready to be merged now then?

**Pull request merged**
