### PR TITLE
release version 3.0.0 beta 5

### PR DESCRIPTION
**Pull request by johanneswilm**
3.0.0 beta 5, containing these additions:

* Browser detection to give warnings to users of untested browsers that will probably not work (such as Internet Explorer and Safari on iOS)
* Addition of notification about browser cookie to follow German and Swedish laws related to the EU cookie directive
* Basic code documentation setup (thanks to Aleksander Korovin of the OSCOSS project)
* Support for running Fidus Writer sites via the secure https/wss as an alternative to http/ws
* Configuration hints for setup where admins receive email messages on server crashes 
* Update of translation strings
* Upgrade of the loadCSS library (now installed via NPM)

### CODE REVIEW

**Comment by zeigerpuppy** [comment]
I tried updating today to test the https feature,
unfortunately it looks like upgrade broke the install.  Documents do not display and cannot be edited, menus are also not working.  No errors in the console.

Upgrade was done on Ubuntu 14.04 with:

```
git pull origin
./manage.py transpile
./manage.py compilemessages
./manage.py migrate
```

then restarted fiduswriter

**Comment by johanneswilm** [comment]
@zeigerpuppy every commit is being sent to Travis, which does a clean installation of Fidus Writer and then performs some tests with it. Only if travis says there are no issues, it is all being merged into upstream.

Additionally, just yesterday a developer reinstalled his test server.

Also, the main test server was updated with this release and more than 5000 previous testers were invited to test it this morning, and none reported any issue like that.

Based on that, I doubt it is entirely broken. But that doesn't mean that not something could be broken. Could you find what kind of error messages you get (JavaScript and Python) and post an issue with those?

**Comment by johanneswilm** [comment]
If you are running this on a production machine, did you remember

./manage.py collectstatic

?

**Comment by zeigerpuppy** [comment]
I did do a collectstatic.
I'll try again tomorrow, needed to rollback for the moment.

**Pull request merged**
