### PR TITLE
Fix document table height

### PR DESCRIPTION
**Pull request by stonfute**
Remove `height: calc(100vh - 320px);` in ` .fw-document-table.fw-large tbody` and ` .fw-document-table.fw-middle tbody`

In order to improve document listing, it would be nice to remove table height in `document_table.css`.
It creates a weird rendering when there's only few documents with too high `<tr>` size.
Moreover, it is not advisable to play on the height while doing responsive design.

See attached screenshots (before and after).

**Before :**
screenshot-2019-1-30 document overview - fidus writer 2
**After :** 
screenshot-2019-1-30 document overview - fidus writer 1

### CODE REVIEW

**Comment by johanneswilm** [comment]
What browser is this on?

**Comment by johanneswilm** [comment]
I see. Firefox. Looks like a Firefox bug. I'll investigate.

**Comment by johanneswilm** [comment]
Another thing. I see you are removing file names from the screenshot, @stonfute . I hope you are not using the development version for production work. I can ensure you that documents created with the development version will break before the next stable version is released. So if that is what you have been doing, please go back to master and copy the documents back using copy and paste. That will be your best bet for at least keeping parts of your documents intact.

**Comment by stonfute** [comment]
Seems to be only on Firefox... 
No problem, my working environment is not on dev version.
I've just used some real documents to test dev environment.

**Comment by johanneswilm** [comment]
@stonfute I have quite a lot to do right now. If you want to make sure I merge this quickly, could you check what it looks like with lots of documents also on Chrome/Chromium? I believe the point of that CSS snippet was to make sure the document table does not get larger than that it can fit within the current page without scrollbars (scrollbars should be shown on the table instead). Maybe we need to change `height` for `max-height`?

**Pull request closed without merging**
