### PR TITLE
Inline Math Editing via ProseMirror NodeView

### PR DESCRIPTION
**Pull request by benrbray**
I'm interested in improving the math editing experience in Fidus Writer.  I'm making this Draft PR to collect some feedback about my proposed changes.  Thanks in advance for your feedback + guidance!

## Motivation

Not everyone works in a field that requires frequent use of math in their text documents, so good math support is often an oversight when developing text editing software.   The current editor based on [MathLive](https://mathlive.io/) is great for people who

* Don't know LaTeX-style math syntax by heart and need extra help finding the symbols they need
* Don't use math frequently enough to be inconvenienced by the extra clicks to bring up the MathLive

However, for users that use math frequently, a math editing experience that requires too much fiddling with menus, modals, etc. can be a deal-breaker.  At the moment, I feel that Fidus Writer falls into this category, and I would like to help out!  See the [screencaps in the linked repository](https://github.com/benrbray/prosemirror-math#examples) for an example of the behavior I'd like to add.

## Integrating with `prosemirror-math`

I am developing a [prosemirror-math plugin](https://github.com/benrbray/prosemirror-math) with the goal of bringing better math editing to existing software based on ProseMirror.

* The goal is for this plugin to be easy drop-in that other ProseMirror-based editors can include without a ton of extra effort.
* MIT License

At the moment, my plugin is a little rough around the edges, so I expect that integration with Fidus Writer will require some improvements to the `prosemirror-math` API.  

## Questions

Before investing time on this, I want to make sure any changes I make align with the goals of Fidus Writer:

- [ ] Would Fidus Writer be receptive to a pull request that includes [this style](https://github.com/benrbray/prosemirror-math#examples) of inline math editing behavior? 
- [ ] What is the recommended way to contribute such a change to Fidus?

## Todos

- [ ] Identify the best way to add an inline math editing plugin to Fidus Writer, including
    * which changes should be made to the JavaScript frontend?
    * which changes, if any, must be made to the Python backend to support the desired behavior?
- [ ] Identify which API changes should be made to my `prosemirror-math` plugin to more easily integrate with Fidus Writer
- [ ] Currently, `prosemirror-math` only supports KaTeX.  Since Fidus Writer appears to use MathView, determine the best way to add [MathLive](https://mathlive.io/) support to `prosemirror-math`.

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @benrbray ,
thanks for this proposal! I think the usefulness of having such an editor depends a lot on the user. When we first started Fidus Writer back in 2012, the general idea was that this was going to be an editor for people who cannot write markdown/LaTeX or any other code and who therefore require a WYSIWYG-alike editor. The main aim was the social sciences. For math formulas we made an exception: math formulas would have to be entered directly in LaTeX-code. The idea was that if you are the kind of user who needs to write formulas, you will likely also be the kind of user who knows to write basic LaTeX.

Over time, with more users joining, we found out that this was actually not the case - there are quite a few users who need to use mathematical formulas who are not able to write LaTeX code. We have changed out the editor we have been using a few times over the years, and have been on Mathlive for a couple of versions without getting too many complaints from users.

So if we were to add something like what you are suggesting, it would have to be done in a way so that power users can make use of it, while less technically-inclined users still have access to some kind of WYSIWYG editor for creating LaTeX formulas. Would that work with how you are planning to developing that plugin?

Also, what would happen in the case of realtime collaboration? If user A enters the formula editor, will user B see the formula editor as well? What is user A enters the formula editor, then forgets about ti and goes to sleep, and then user B tries to export the document to DOCX?

**Comment by benrbray** [comment]
Thanks for your feedback!

> So if we were to add something like what you are suggesting, it would have to be done in a way so that power users can make use of it, while less technically-inclined users still have access to some kind of WYSIWYG editor for creating LaTeX formulas. Would that work with how you are planning to developing that plugin?

Absolutely!  I definitely see the value in the current style of math editing for some users, and I wouldn't want to remove it.  I think, best case, Fidus Writer would support both options simultaneously.  So, there would be two ways to add math to a document:

1. Click the existing "%" button to open the MathLive editor, from which the user can create a math block.
2. In the normal editor, use a [ProseMirror input rule](https://prosemirror.net/docs/ref/#inputrules) to detect when the user starts (or finishes) typing a math expression like `$\int_a^b f(x) dx$`.
    * I'm using the standard delimiters `$...$` and `$$...$$` here, but this can be changed

Now, the part I'm not sure of is:  can we use Method 1 to edit a math block created with Method 2, and vice versa?  Ideally, the answer would be yes, but this depends on:

- [ ] whether MathLive can accept LaTeX notation as input to its visual editor (I'm not sure)
- [x] whether MathLive can output LaTeX for math created with its visual editor (appears to be true)

I've uploaded a [DEMO of my prosemirror-math plugin](https://benrbray.com/static/prosemirror-math/index.html) so you can get a better idea of the type of math editing experience I'd like to see in Fidus Writer (and all other note-taking software!!)

* For inline math, type a math expression like $a+b=c$, and the math will be rendered as soon as you're done typing the rightmost `$`
* For block math, create a new line and type `$$` followed by a space.  You can press CTRL+Enter to leave the math block.

> Also, what would happen in the case of realtime collaboration? If user A enters the formula editor, will user B see the formula editor as well? What is user A enters the formula editor, then forgets about ti and goes to sleep, and then user B tries to export the document to DOCX?

Great questions!  I think it depends on the goals of Fidus Writer, so I'd appreciate some guidance in picking the correct approach.  

* I'm new to Fidus so I haven't had a chance to use it collaboratively--how does the current MathLive editor work with collaboration?
* Where's the best place to look (in the code/docs) if I want to better understand Fidus Writer's internal appraoch to collaboration / merge resolution /etc?

I can imagine a few different options:

1. Make the new "inline" math editor entirely a "client-side" concept, by only "committing" changes to the math block whenever the user LEAVES the math editing mode, rather than on every key stroke.  I'm not sure if this is desirable from a UX standpoint though, as that behavior may not be intuitively obvious.
    * Is this how the MathLive editor currently works collaboratively?
2. Alternatively, store the "expand/collapse" state of each math node as part of the document.  If UserA "expands" a math node, UserB will see it expanded as well, until it is closed.  This option would offer a similar experience to editing a raw .tex file e.g. on ShareLaTeX.

**Comment by johanneswilm** [comment]
> This should be technically possible since it appears that...

Yes, we are only storing the math as LaTex. So it is this LaTeX we are feeding into Mathlive when the editor is invoked.

> Make the new "inline" math editor entirely a "client-side" concept, by only "committing" changes to the math block whenever the user LEAVES the math editing mode, rather than on every key stroke. I'm not sure if this is desirable from a UX standpoint though, as that behavior may not be intuitively obvious.
Is this how the MathLive editor currently works collaboratively?

Yes, that is how it works currently. Given that any client can only have the selection in one place at any given time, it may be enough to just pause submitting changes until the formula editing operation has finished.

I agree that there may be some situations in which this is not entirely obvious to end users, but I think that is a cost worth paying if it means we can ensure that the document can be printed/exported at any given time and that it is always has a valid state. The other proposed solution may also work, but it seems like there may be a lot more edge cases and potential problems to take care of, including issues when more technically inclined users collaborate on a document with less technical users. But if you want to take on those challenges, then we can also try that.

As for how to submit changes to FW - making a proposal the way you did here is a good beginning. After that, we only require signing the CLA and going through a code review that I will conduct once we have something to look at.

**Comment by johanneswilm** [comment]
It looks like this project is not going anywhere, so I'll close it. Please reopen if you want to do it anyway.

**Pull request closed without merging**
