### PR TITLE
Brazilian translation, thanks to @jobdiogenes !

### PR DESCRIPTION
**Pull request by johanneswilm**

### CODE REVIEW

**Comment by johanneswilm** [comment]
@jobdiogenes I have added Brazilian Portuguese to the relevant menu and updates the message list. But you still need to sign the CLA here [1] before I can merge this.

[1] http://www.clahub.com/agreements/fiduswriter/fiduswriter

**Comment by johanneswilm** [comment]
@jobdiogenes Ping! Are you still interested in getting this merged?

**Comment by jobdiogenes** [comment]
Hello Johannes,

Yes I still interested, but as anyone who contribute to opensource projects, want to safeguard the credit by the work done.  So in the agreement say "You also waive and/or agree not to assert against FIDUS or its licensees any moral rights that You may have on Your Contribution.", could be understood that the contributor could loose the credits for their contribution.  is it?

**Comment by johanneswilm** [comment]
@jobdiogenes You are not signing over the copyright for your code. You will always have that. Your moral rights include the right to keep your work as one "integrated piece". Which could mean that if you don't grant us this right, you could start suing us in 5 years time because someone else updated your translation. Should you decide not to contribute any more or simply disappear, and someone else come forward and offer Brazilian Portuguese translations, then your name in the field "Last-Translator" field would be exchanged with the name of the new translator.

The agreement is a standardized agreement that some other groups have written in the past. I am not a lawyer, so if you don't feel comfortable with it, you are of course free not to sign it.

**Comment by johanneswilm** [comment]
@jobdiogenes Thanks for signing it!

**Pull request merged**
